### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'Seq' and 'int'

### ISSUE THREAD

**Issue by baishengjun** [ryought/hic_hiker#3]
Hi,

I encounter an errror when I run hic_hiker.
It is my commondline : ` hic_hiker --fasta  curated.fasta --assembly curated.final.assembly --mnd merged_nodups.txt  -K 20000 --refsam deltoides.final.sam ./run_hicliker`
and it fails 
`Traceback (most recent call last):
  File "/mnt/sdf1/boshengjun/miniconda3/bin/hic_hiker", line 11, in <module>
    load_entry_point('hic-hiker', 'console_scripts', 'hic_hiker')()
  File "/mnt/sda/boshengjun/hic_hiker/hic_hiker/main.py", line 186, in main
    add_gap=True,
  File "/mnt/sda/boshengjun/hic_hiker/hic_hiker/layout.py", line 180, in get_fasta
    scaf_sequence += Seq('N') * 500
TypeError: unsupported operand type(s) for *: 'Seq' and 'int'
`
how can I solve this problem ? 

Thanks in advance,
Bai

**Comment by baishengjun** [comment]
HI,

I update the python version, the previous problem sovled.
but encounter a new error:
`Traceback (most recent call last):
  File "/mnt/sdf1/boshengjun/miniconda3/envs/py_newest/bin/hic_hiker", line 33, in <module>
    sys.exit(load_entry_point('hic-hiker', 'console_scripts', 'hic_hiker')())
  File "/mnt/sda/boshengjun/HIKER/hic_hiker/hic_hiker/main.py", line 210, in main
    figures.fig_matrix(probs, contigs, polished_layouts[3], original_layout, results[3])
  File "/mnt/sda/boshengjun/HIKER/hic_hiker/hic_hiker/figures.py", line 143, in fig_matrix
    _inspect_with_size(probs, polished_layout, ori_layout, contigs, result, scaf_id=0, pos=i)
  File "/mnt/sda/boshengjun/HIKER/hic_hiker/hic_hiker/figures.py", line 207, in _inspect_with_size
    orientations = [
  File "/mnt/sda/boshengjun/HIKER/hic_hiker/hic_hiker/figures.py", line 208, in <listcomp>
    0 if polished_layout.scaffolds[scaf_id].orientation[x] == ori_layout.scaffolds[scaf_id].orientation[x] else 1
IndexError: list index out of range
`
How to solve it?
 
Thanks in advance
Bai
